
import { Contact, CustomerStatus, DealStage } from '../types';

export const MOCK_CUSTOMER_DATA: Contact[] = [
  {
    id: '1',
    company: '3JDS CALIBRATION CENTER',
    pastName: '3JDS Calibration Services',
    customerSince: '2019-05-24',
    team: 'North Team',
    salesman: 'James Quek',
    referBy: 'Walk-in',
    address: '#20 Guyong',
    province: 'Bulacan',
    city: 'Sta. Maria',
    deliveryAddress: '#20 Guyong Sta. Maria Bulacan',
    area: 'BULACAN',
    tin: '123-456-789',
    priceGroup: 'VIP2',
    businessLine: 'Diesel Calibration',
    terms: 'AP/TT-PNB',
    transactionType: 'Order Slip',
    vatType: 'Exclusive',
    vatPercentage: '12',
    dealershipTerms: 'Standard',
    dealershipSince: '2019',
    dealershipQuota: 100000,
    creditLimit: 50000,
    status: CustomerStatus.ACTIVE,
    isHidden: false,
    debtType: 'Bad',
    comment: 'Consistent orders but slow pay.',
    contactPersons: [
        { id: 'cp1', enabled: true, name: 'Geraldine Concepcion', position: 'Owner', birthday: '1985-05-12', telephone: '', mobile: '0917-8869038', email: 'geraldine@3jds.com' }
    ],
    name: 'Geraldine Concepcion',
    title: 'Owner',
    email: '',
    phone: '0917-8869038',
    avatar: 'https://i.pravatar.cc/150?u=3jds',
    dealValue: 0,
    stage: DealStage.CLOSED_WON,
    lastContactDate: '2023-11-01',
    assignedAgent: 'James Quek',
    totalSales: 177225.00,
    balance: 88801.00,
    salesByYear: { 
        '2019': 177225.00,
        '2020': 165000.00,
        '2021': 140000.00,
        '2022': 180000.00,
        '2023': 88801.00
    },
    topProducts: [],
    salesHistory: [],
    comments: [],
    interactions: []
  },
  {
    id: '2',
    company: 'CD MACHINEWORK CALIBRATION',
    pastName: 'CD Calibration Services',
    customerSince: '2013-06-21',
    team: 'Mindanao Team',
    salesman: 'Sarah Sales',
    referBy: 'Referral',
    address: 'Purok 7, Gusa Highway',
    province: 'Misamis Oriental',
    city: 'Cagayan De Oro',
    deliveryAddress: 'AP EXPRESS : PUROK 7, GUSA HIGHWAY...',
    area: 'CAGAYAN DE ORO CITY',
    tin: '707-993-646',
    priceGroup: 'VIP2',
    businessLine: 'Diesel Calibration',
    terms: 'AP/TT-PNB',
    transactionType: 'Order Slip',
    vatType: 'Exclusive',
    vatPercentage: '12',
    dealershipTerms: 'Premium',
    dealershipSince: '2013',
    dealershipQuota: 500000,
    creditLimit: 100000,
    status: CustomerStatus.ACTIVE,
    isHidden: false,
    debtType: 'Good',
    comment: 'Top tier client.',
    contactPersons: [
        { id: 'cp2', enabled: true, name: 'Glorian Iniego Cabana', position: 'Owner', birthday: '', telephone: '', mobile: '09176587765', email: '' }
    ],
    name: 'GLORIAN INIEGO CABANA',
    title: 'Owner',
    email: '',
    phone: '09176587765',
    mobile: '09176587765',
    avatar: 'https://i.pravatar.cc/150?u=cdmachine',
    dealValue: 0,
    stage: DealStage.CLOSED_WON,
    lastContactDate: '2023-10-15',
    assignedAgent: 'Sarah Sales',
    totalSales: 885481.00,
    balance: 96775.00,
    salesByYear: { 
        '2019': 142000.00, 
        '2020': 125000.00, 
        '2021': 98000.00, 
        '2022': 135830.00, 
        '2023': 39480.00 
    },
    topProducts: [],
    salesHistory: [],
    comments: [],
    interactions: []
  },
  {
    id: '3',
    company: '3R AND 3A CALIBRATION',
    pastName: '3R Calibration',
    customerSince: '2020-03-03',
    team: 'South Team',
    salesman: 'Sarah Sales',
    referBy: '',
    address: 'Blk 2 Lot 18 Grand River Stone',
    province: 'Laguna',
    city: 'Sta. Rosa',
    deliveryAddress: 'Same as Office',
    area: 'LAGUNA',
    tin: '',
    priceGroup: 'VIP1',
    businessLine: 'Diesel Calibration',
    terms: 'AP/TT-PNB',
    transactionType: 'Order Slip',
    vatType: 'Exclusive',
    vatPercentage: '12',
    dealershipTerms: '',
    dealershipSince: '',
    dealershipQuota: 0,
    creditLimit: 0,
    status: CustomerStatus.INACTIVE,
    isHidden: true,
    debtType: 'Good',
    comment: 'Seasonal buyer',
    contactPersons: [
        { id: 'cp3', enabled: true, name: 'Richard A. Penaflor', position: 'Manager', birthday: '', telephone: '0917-1271456', mobile: '0950-4145 264', email: '' }
    ],
    name: 'RICHARD A. PENAFLOR',
    title: '',
    email: '',
    phone: '0917-1271456',
    avatar: 'https://i.pravatar.cc/150?u=3r3a',
    dealValue: 0,
    stage: DealStage.CLOSED_WON,
    lastContactDate: '2023-09-20',
    assignedAgent: 'Sarah Sales',
    totalSales: 131335.00,
    balance: 52049.88,
    salesByYear: { 
        '2019': 45000.00,
        '2020': 55065.00, 
        '2021': 60000.00,
        '2022': 25000.00,
        '2023': 18760.00 
    },
    topProducts: [],
    salesHistory: [],
    comments: [],
    interactions: []
  },
  {
    id: '4',
    company: '4 DA BOYS MOTORCYCLE SHOP',
    pastName: '4 DA BOYS MC Shop',
    customerSince: '2019-07-31',
    team: 'Metro Team',
    salesman: 'James Quek',
    referBy: '',
    address: 'Luzon Ave, Makasampa',
    province: 'NCR',
    city: 'Quezon City',
    deliveryAddress: 'Same',
    area: 'QUEZON CITY',
    tin: '',
    priceGroup: 'AA',
    businessLine: 'Motorcycle Shop',
    terms: 'COD',
    transactionType: 'Order Slip',
    vatType: 'Inclusive',
    vatPercentage: '12',
    dealershipTerms: '',
    dealershipSince: '',
    dealershipQuota: 0,
    creditLimit: 20000,
    status: CustomerStatus.BLACKLISTED,
    isHidden: false,
    debtType: 'Bad',
    comment: 'Do not sell until balance paid',
    contactPersons: [
        { id: 'cp4', enabled: true, name: 'Mohatmen Sultan', position: 'Owner', birthday: '', telephone: '', mobile: '09464377575', email: '' }
    ],
    name: 'MOHATMEN SULTAN',
    title: '',
    email: '',
    phone: '',
    mobile: '09464377575',
    avatar: 'https://i.pravatar.cc/150?u=4daboys',
    dealValue: 0,
    stage: DealStage.CLOSED_LOST,
    lastContactDate: '2023-07-22',
    assignedAgent: 'James Quek',
    totalSales: 32300.00,
    balance: 9000.00,
    salesByYear: { 
        '2019': 23250.00,
        '2020': 15000.00,
        '2021': 10000.00,
        '2022': 5000.00,
        '2023': 0.00
    },
    topProducts: [],
    salesHistory: [],
    comments: [],
    interactions: []
  },
   {
    id: '5',
    company: 'AGA AUTO PARTS',
    pastName: 'AGA Auto Supply',
    customerSince: '2018-09-24',
    team: 'Mindanao Team',
    salesman: 'Esther Van',
    referBy: '',
    address: 'AP Building Zone 7',
    province: 'Misamis Oriental',
    city: 'Cagayan De Oro',
    deliveryAddress: 'Same',
    area: 'CAGAYAN DE ORO CITY',
    tin: '422-118-127',
    priceGroup: 'CC',
    businessLine: 'Auto Supply',
    terms: 'AP',
    transactionType: 'Invoice',
    vatType: 'Inclusive',
    vatPercentage: '12',
    dealershipTerms: '',
    dealershipSince: '',
    dealershipQuota: 0,
    creditLimit: 0,
    status: CustomerStatus.PROSPECTIVE,
    isHidden: false,
    debtType: 'Good',
    comment: 'Potential for high volume',
    contactPersons: [
        { id: 'cp5', enabled: true, name: 'Rafael Amboy', position: 'Owner', birthday: '', telephone: '', mobile: '09175183332', email: '' }
    ],
    name: 'RAFAEL AMBOY',
    title: '',
    email: '',
    phone: '',
    mobile: '09175183332',
    avatar: 'https://i.pravatar.cc/150?u=aga',
    dealValue: 0,
    stage: DealStage.PROPOSAL,
    lastContactDate: '2023-10-05',
    assignedAgent: 'Esther Van',
    totalSales: 789385.00,
    balance: 70674.00,
    salesByYear: { 
        '2018': 474560.00, 
        '2019': 350000.00,
        '2020': 200000.00,
        '2021': 180000.00,
        '2022': 150000.00,
        '2023': 145470.00 
    },
    topProducts: [],
    salesHistory: [],
    comments: [],
    interactions: []
  }
];
