CREATE TABLE IF NOT EXISTS public.access_groups (
  id bigint generated by default as identity primary key,
  main_id integer not null,
  name varchar(255) not null,
  description varchar(255),
  access_rights jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

ALTER TABLE public.access_groups ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access for authenticated users" ON public.access_groups
FOR SELECT TO authenticated
USING (true);

CREATE POLICY "Allow write access for Managers and Owners" ON public.access_groups
FOR ALL TO authenticated
USING (
  exists (
    select 1 from profiles
    where id = auth.uid()
    and role in ('Owner', 'Manager', 'Admin', 'Developer')
  )
)
WITH CHECK (
  exists (
    select 1 from profiles
    where id = auth.uid()
    and role in ('Owner', 'Manager', 'Admin', 'Developer')
  )
);

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS group_id bigint references public.access_groups(id) on delete set null;
